apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - limit-range.yaml
  - namespace.yaml
  - object-store.yaml
  - resource-quota.yaml
  - scheduled-backup.yaml
  - storage-class.yaml
