apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-alloy-events
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.externalCharts.alloy.repoURL | quote }}
    chart: alloy
    targetRevision: {{ .Values.externalCharts.alloy.version | quote }}
    helm:
      releaseName: observability-events-collector
      values: |
{{ .Files.Get "files/logging/alloy-events-values.yaml" | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
