apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing-tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.git.repoURL | quote }}
    targetRevision: {{ .Values.git.targetRevision | quote }}
    path: platform/tracing/tempo
    helm:
      releaseName: observability-tempo
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
