apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-cnpg
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/part-of: startup-devops-baseline
    app.kubernetes.io/managed-by: argocd
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
  iops: "3000"
  throughput: "125"
  csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
