image:
  repository: ghcr.io/sterlingaureum/startup-devops-baseline/demo-api
  tag: "sha-44af462"
  digest: "sha256:85689ab373c423fb825f02b10b6b03b293a764583f86ddef6e48746d522918e5"

release:
  applicationVersion: "sha-44af462"

delivery:
  sourceRepository: "SterlingAureum/startup-devops-baseline"
  sourceCommit: "44af462922ccecd053c7926e8b811ed9a1dcf00d"
  workflowRunId: "31874680388"
