image:
  repository: ghcr.io/sterlingaureum/startup-devops-baseline/demo-api
  tag: "sha-e43b535"
  digest: "sha256:45744978f664522cc3c952eba6e358aba261640338fa6d39820f165c18dbc5b0"

release:
  applicationVersion: "sha-e43b535"

delivery:
  sourceRepository: "SterlingAureum/startup-devops-baseline"
  sourceCommit: "e43b535a1dd802c221a24c0bfde3c471c6a5df5f"
  workflowRunId: "31950329805"
