image:
  repository: ghcr.io/sterlingaureum/startup-devops-baseline/demo-api
  tag: "sha-881b537"
  digest: "sha256:b794221948ec2d12ccab5c64b801cdde9c399ea899fa43031f6b923479ffeae8"

release:
  applicationVersion: "sha-881b537"

delivery:
  sourceRepository: "SterlingAureum/startup-devops-baseline"
  sourceCommit: "881b537e31141d0be857feeaae83b34d40e560a5"
  workflowRunId: "31702339329"
