image:
  repository: ghcr.io/sterlingaureum/startup-devops-baseline/demo-api
  tag: "sha-535a69e"
  digest: "sha256:5d08f0f409a191cc60affc6e645379aef9c39abdd8982bd387ac1d5d9ced0b3f"

release:
  applicationVersion: "sha-535a69e"

delivery:
  sourceRepository: "SterlingAureum/startup-devops-baseline"
  sourceCommit: "535a69e872595026b5f36e7259908c8bbb947741"
  workflowRunId: "31887643150"
