image:
  repository: ghcr.io/sterlingaureum/startup-devops-baseline/demo-api
  tag: "sha-04ca5ab"
  digest: "sha256:fcfa4f473dd0f2752e73f885cd3e372cfdcc1f468222e425d0f2a18e8c2c8abc"

release:
  applicationVersion: "sha-04ca5ab"

delivery:
  sourceRepository: "SterlingAureum/startup-devops-baseline"
  sourceCommit: "04ca5ab03d999d138c5187c9745f91749bd39f07"
  workflowRunId: "31196357498"
