replicaCount: 3

image:
  repository: ghcr.io/sterlingaureum/startup-devops-baseline/demo-api
  tag: "sha-61b5677"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rollout:
  enabled: true
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 0
      stableService: demo-api-stable
      canaryService: demo-api-canary
      trafficRouting:
        nginx:
          enabled: true
          stableIngress: demo-api
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 50
        - pause:
            duration: 30s
        - setWeight: 100

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 10001

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

containerPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: demo-api.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /ready
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

env:
  APP_NAME: demo-api
  APP_VERSION: "sha-61b5677"
  APP_ENV: local

nodeSelector: {}
tolerations: []
affinity: {}
