replicaCount: 2

image:
  repository: ghcr.io/sterlingaureum/startup-devops-baseline/demo-api
  tag: "sha-983167a"
  digest: "sha256:2de53fd2371377019cc608bb65a5187e327798b7e9fe36db1f8273f1fcb5bd54"
  pullPolicy: IfNotPresent

rollout:
  enabled: false

analysis:
  enabled: false

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=true
  hosts:
    - host: demo.dev.aureumstack.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

readinessProbe:
  timeoutSeconds: 10

env:
  APP_NAME: demo-api
  APP_VERSION: "sha-983167a"
  APP_ENV: aws-dev

database:
  enabled: true
  secretName: demo-api-postgresql
  secretKey: DATABASE_URL
  connectTimeoutSeconds: 2
  retryAttempts: 3
  retryDelaySeconds: 1

delivery:
  sourceRepository: "SterlingAureum/startup-devops-baseline"
  sourceCommit: "983167adcae0d9b0397825027091b4a0a1c57532"
  workflowRunId: "30356690212"
