replicaCount: 2

image:
  repository: ghcr.io/sterlingaureum/startup-devops-baseline/demo-api
  tag: "sha-49b7d96"
  digest: "sha256:30e9c80b6a808375b9261120f94d6518bf27481953347198d2f16e74c370489e"
  pullPolicy: IfNotPresent

rollout:
  enabled: false

analysis:
  enabled: false

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=true
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

readinessProbe:
  timeoutSeconds: 10

env:
  APP_NAME: demo-api
  APP_VERSION: "sha-49b7d96"
  APP_ENV: aws-dev

database:
  enabled: true
  secretName: demo-api-postgresql
  secretKey: DATABASE_URL
  connectTimeoutSeconds: 2
  retryAttempts: 3
  retryDelaySeconds: 1

delivery:
  sourceRepository: "SterlingAureum/startup-devops-baseline"
  sourceCommit: "49b7d9643adb4f6bed91f17414d1c7bf18042ef7"
  workflowRunId: "30364950279"
