apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: startup-apps
  labels:
    app.kubernetes.io/part-of: startup-devops-baseline
    platform.startup.dev/environment: aws-dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
