apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-admission-policies-aws-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SterlingAureum/startup-devops-baseline.git
    targetRevision: main
    path: platform/security/admission-policies/application-workloads
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: startup-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
