apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-views-aws-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SterlingAureum/startup-devops-baseline.git
    targetRevision: main
    path: platform/observability/helm
    helm:
      releaseName: observability-views
      parameters:
        - name: environment
          value: aws-dev
        - name: cluster
          value: startup-devops-baseline-dev
        - name: controllerMonitors.cloudNativePG.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
