apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../base/security/network-policies/data-platform
labels:
  - pairs:
      platform.startup.dev/environment: aws-dev
