apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-platform-network-policy-aws-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "45"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SterlingAureum/startup-devops-baseline.git
    targetRevision: feature/v0.8-production-security-baseline
    path: clusters/aws-dev/security/network-policies/data-platform
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
