apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.8.0
    helm:
      releaseName: external-secrets
      valuesObject:
        installCRDs: true
        crds:
          createClusterExternalSecret: false
          createClusterSecretStore: false
          createClusterGenerator: false
          createClusterPushSecret: false
          createPushSecret: false
          createSecretStore: true
        leaderElect: true
        scopedRBAC: true
        scopedNamespace: startup-apps
        processClusterExternalSecret: false
        processClusterPushSecret: false
        processClusterStore: false
        processClusterGenerator: false
        processPushSecret: false
        rbac:
          serviceAccountTokenCreate: false
          servicebindings:
            create: false
          aggregateToView: false
          aggregateToEdit: false
          aggregateToAdmin: false
        serviceAccount:
          create: false
          name: external-secrets
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: karpenter.sh/nodepool
                      operator: DoesNotExist
                    - key: workload
                      operator: In
                      values:
                        - system
        webhook:
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: karpenter.sh/nodepool
                        operator: DoesNotExist
                      - key: workload
                        operator: In
                        values:
                          - system
        certController:
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: karpenter.sh/nodepool
                        operator: DoesNotExist
                      - key: workload
                        operator: In
                        values:
                          - system
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
