apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-startup-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SterlingAureum/startup-devops-baseline.git
    targetRevision: feature/v0.8-production-security-baseline
    path: clusters/aws-dev/security/external-secrets/startup-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: startup-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
