apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: 1.14.0
    helm:
      releaseName: karpenter
      skipCrds: true
      values: |
        settings:
          clusterName: startup-devops-baseline-dev
          interruptionQueue: startup-devops-baseline-dev-karpenter-interruptions
        serviceAccount:
          create: false
          name: karpenter
        replicas: 2
        controller:
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: karpenter.sh/nodepool
                      operator: DoesNotExist
                    - key: workload
                      operator: In
                      values:
                        - system
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: karpenter
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
