apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-baseline
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  project: default
  source:
    repoURL: https://github.com/SterlingAureum/startup-devops-baseline.git
    targetRevision: feature/v0.6-cloudnativepg-data-platform
    path: clusters/aws-dev/data-platform/postgresql
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
