apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: startup-apps
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-egress
  namespace: startup-apps
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-alb-to-demo-api
  namespace: startup-apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: demo-api
      app.kubernetes.io/instance: demo-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 10.20.0.0/24
        - ipBlock:
            cidr: 10.20.1.0/24
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-argo-rollouts-analysis-to-demo-api
  namespace: startup-apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: demo-api
      app.kubernetes.io/instance: demo-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: argo-rollouts
          podSelector:
            matchLabels:
              app.kubernetes.io/name: argo-rollouts
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-demo-api-to-postgresql
  namespace: startup-apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: demo-api
      app.kubernetes.io/instance: demo-api
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: data-platform
              platform.startup.dev/tier: data
          podSelector:
            matchLabels:
              cnpg.io/cluster: postgresql-baseline
      ports:
        - protocol: TCP
          port: 5432
