apiVersion: v1
kind: LimitRange
metadata:
  name: startup-apps-containers
  namespace: startup-apps
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 10m
        memory: 32Mi
      max:
        cpu: "2"
        memory: 2Gi
