apiVersion: v1
kind: ResourceQuota
metadata:
  name: startup-apps
  namespace: startup-apps
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "20"
    services: "10"
    configmaps: "20"
    secrets: "30"
    persistentvolumeclaims: "5"
    requests.storage: 50Gi
