apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "startup-devops-tempo.fullname" . }}
  labels:
    {{- include "startup-devops-tempo.labels" . | nindent 4 }}
automountServiceAccountToken: false
