apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: startup-devops-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/startup-devops-baseline.git
    targetRevision: HEAD
    path: clusters/local/platform
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
