apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: startup-devops-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SterlingAureum/startup-devops-baseline.git
    targetRevision: HEAD
    path: clusters/local/platform
    helm:
      parameters:
        - name: git.repoURL
          value: https://github.com/SterlingAureum/startup-devops-baseline.git
        - name: git.targetRevision
          value: HEAD
        - name: demoApi.localImage.enabled
          value: "false"
        - name: demoApi.localImage.repository
          value: startup-devops-baseline/demo-api
        - name: demoApi.localImage.tag
          value: ""
        - name: demoApi.localImage.pullPolicy
          value: Never
        - name: demoApi.localImage.applicationVersion
          value: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
