name: validate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm lint
        run: |
          helm lint apps/demo-api/helm

      - name: Helm template validation
        run: |
          helm template demo-api apps/demo-api/helm > /tmp/demo-api-rendered.yaml

      - name: Docker build validation
        run: |
          docker build -t demo-api-ci-test apps/demo-api

      - name: Hadolint Dockerfile check
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: apps/demo-api/Dockerfile
